// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _main_palette_H_
#define _main_palette_H_

#include <types.h>

extern const u8 main_palette[16];

#endif
